name: Flutter APK Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. 소스 체크아웃
    - uses: actions/checkout@v3

    # 2. Flutter SDK 캐싱
    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/flutter
        key: flutter-sdk-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}

    # 3. Flutter 세팅
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'

    # 4. Android cmdline-tools 설치
    - name: Install Android cmdline-tools
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
        curl -fo commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        sudo unzip commandlinetools.zip -d /usr/local/lib/android/sdk/cmdline-tools
        sudo mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_ENV

    # 5. Android SDK & NDK 설치
    - name: Install Android SDK & NDK
      run: |
        yes | sdkmanager --licenses
        sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        sdkmanager --install "ndk;28.2.13676358" "cmake;3.22.1"

    # 6. 환경 변수 등록 (NDK 경로 지정)
    - name: Set NDK environment variable
      run: |
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> $GITHUB_ENV

    # 7. Pub 패키지 캐싱
    - name: Cache Pub packages
      uses: actions/cache@v4
      with:
        path: ~/.pub-cache
        key: pub-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          pub-${{ runner.os }}-

    - name: Install dependencies
      run: flutter pub get

    # 8. Gradle 캐싱
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    # 9. APK 빌드
    - name: Build APK
      run: flutter build apk --release

    # 10. 결과 업로드
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk